[env:esp32-fastled]
platform = espressif32@6.5.0
board = az-delivery-devkit-v4
framework = arduino

upload_port = COM5
upload_speed = 921600
upload_protocol = esptool

build_type = release
build_flags = 
  -D FASTLED_ESP32_I2S            ; Stabilerer Treiber für ESP32
  -Wno-deprecated-declarations    ; Unterdrückt veraltete Warnungen

monitor_speed = 115200
monitor_filters = 
	esp32_exception_decoder
	default

lib_deps = 
	fastled/FastLED@^3.9.4
	esphome/ESPAsyncWebServer-esphome@^3.2.2
	;winlinvip/SimpleDHT@^1.0.15
	;me-no-dev/AsyncTCP@^3.3.2
	;paulstoffregen/Encoder@^1.4.4
	;madhephaestus/ESP32Encoder@^0.11.7